import { FuseNavigationItem } from '@fuse/components/navigation';
import { ROLE_KEY_ADMINISTRATOR } from 'app/shared/constants/role-keys';

export const adminNavigation: FuseNavigationItem[] = [
  {
    id: 'home',
    title: 'navigation.home',
    type: 'basic',
    icon: 'heroicons_solid:home',
    link: '/sponsors',
    roles: [ROLE_KEY_ADMINISTRATOR],
  },
  {
    id: 'documents',
    title: 'navigation.documents',
    type: 'basic',
    icon: 'heroicons_solid:document-duplicate',
    link: '/documents',
    roles: [ROLE_KEY_ADMINISTRATOR],
  },
  {
    id: 'reports',
    title: 'navigation.reports',
    type: 'basic',
    icon: 'heroicons_solid:document-chart-bar',
    link: '/reports',
    roles: [ROLE_KEY_ADMINISTRATOR],
  },
  {
    id: 'administration',
    title: 'navigation.administration.title',
    type: 'group',
    icon: 'heroicons_solid:building-office',
    children: [
      {
        id: 'administration.agency-status',
        title: 'navigation.administration.agency-status',
        type: 'basic',
        icon: 'heroicons_solid:building-office',
        link: '/agency-status',
      },
      {
        id: 'administration.agency-status-history',
        title: 'navigation.administration.agency-status-history',
        type: 'basic',
        icon: 'heroicons_solid:clock',
        link: '/agency-status-history',
      },
      {
        id: 'administration.kitchen-types',
        title: 'navigation.administration.kitchen-types',
        type: 'basic',
        icon: 'heroicons_solid:building-office',
        link: '/kitchen-type',
      },
      {
        id: 'administration.residential-types',
        title: 'navigation.administration.residential-types',
        type: 'basic',
        icon: 'heroicons_solid:building-office',
        link: '/residential-type',
      },
      {
        id: 'administration.organization-types',
        title: 'navigation.administration.organization-types',
        type: 'basic',
        icon: 'heroicons_solid:building-office',
        link: '/organization-type',
      },
      {
        id: 'administration.group-types',
        title: 'navigation.administration.group-types',
        type: 'basic',
        icon: 'heroicons_solid:building-office',
        link: '/group-type',
      },
      {
        id: 'administration.sponsor-types',
        title: 'navigation.administration.sponsor-types',
        type: 'basic',
        icon: 'heroicons_solid:building-office',
        link: '/sponsor-type',
      },
      {
        id: 'administration.staff-types',
        title: 'navigation.administration.staff-types',
        type: 'basic',
        icon: 'heroicons_solid:user-group',
        link: '/staff-type',
      },
      {
        id: 'administration.operating-policies',
        title: 'navigation.administration.operating-policies',
        type: 'basic',
        icon: 'heroicons_solid:building-office',
        link: '/operating-policy',
      },
      {
        id: 'administration.email',
        title: 'navigation.administration.email',
        type: 'collapsable',
        icon: 'heroicons_solid:envelope',
        children: [
          {
            id: 'administration.email-templates',
            title: 'navigation.administration.email-templates',
            type: 'basic',
            icon: 'heroicons_solid:envelope',
            link: '/email-template',
          },
          {
            id: 'administration.email-logs',
            title: 'navigation.administration.email-logs',
            type: 'basic',
            icon: 'heroicons_solid:envelope-open',
            link: '/email-logs',
          },
        ],
      },
      {
        id: 'administration.logs',
        title: 'navigation.administration.logs',
        type: 'basic',
        icon: 'heroicons_solid:document-text',
        link: '/logs',
      },
      {
        id: 'administration.message-templates',
        title: 'navigation.administration.message-templates',
        type: 'basic',
        icon: 'heroicons_solid:chat-bubble-left-right',
        link: '/message-template',
      },
    ],
    roles: [ROLE_KEY_ADMINISTRATOR],
  },
  {
    id: 'users',
    title: 'navigation.users.title',
    type: 'group',
    icon: 'heroicons_solid:user',
    children: [
      {
        id: 'users.nutre',
        title: 'navigation.nutre.title',
        type: 'basic',
        icon: 'heroicons_solid:user',
        link: '/users',
      },
      {
        id: 'users.auspiciadores',
        title: 'navigation.auspiciadores.title',
        type: 'basic',
        icon: 'heroicons_solid:building-office-2',
        link: '/users-agency',
      },
    ],
  },
  {
    id: 'staff',
    title: 'navigation.staff.title',
    type: 'group',
    icon: 'heroicons_solid:user-group',
    children: [
      {
        id: 'staff.employees',
        title: 'navigation.staff.employees',
        type: 'basic',
        icon: 'heroicons_solid:users',
        link: '/staff/employees',
      },
      {
        id: 'staff.board-members',
        title: 'navigation.staff.board-members',
        type: 'basic',
        icon: 'heroicons_solid:user-group',
        link: '/staff/board-members',
      },
    ],
  }
];
