import { FuseNavigationItem } from '@fuse/components/navigation';

export const agencyNavigation: FuseNavigationItem[] = [
//   {
//     id: 'agency-home',
//     title: 'navigation.agency.home',
//     type: 'basic',
//     icon: 'heroicons_outline:home',
//     link: '/program-requests',
//   },
  {
    id: 'program-requests',
    title: 'navigation.agency.program-requests',
    type: 'basic',
    icon: 'heroicons_outline:document-text',
    link: '/program-requests',
    //permissions: ['ProgramRequestView'],
  },
  {
    id: 'legibility',
    title: 'navigation.agency.legibility',
    type: 'basic',
    icon: 'heroicons_outline:document-text',
    link: '/legibility',
    permissions: ['LegibilityView'],
  },
//   {
//     id: 'users',
//     title: 'navigation.users.title',
//     type: 'group',
//     icon: 'heroicons_solid:user',
//     children: [
//       {
//         id: 'users.list',
//         title: 'navigation.users.list',
//         type: 'basic',
//         icon: 'mat_solid:list',
//         link: '/users',
//       },
//       {
//         id: 'users.add',
//         title: 'navigation.users.add',
//         type: 'basic',
//         icon: 'mat_solid:add',
//         link: '/users/add',
//       },
//       {
//         id: 'roles.list',
//         title: 'navigation.users.roles',
//         type: 'basic',
//         icon: 'mat_solid:lock',
//         link: '/users/roles',
//       },
//     ],
//   },
  // Otros ítems específicos de Agency-Administrator
  {
    id: 'documents.agency',
    title: 'navigation.documents',
    type: 'basic',
    icon: 'heroicons_solid:document-duplicate',
    link: '/documents',
    roles: ['Agency-Administrator'],
    permissions: ['DocumentView'],
  },
  {
    id: 'schools',
    title: 'navigation.schools',
    type: 'basic',
    icon: 'heroicons_outline:academic-cap',
    link: '/schools',
    roles: ['Agency-Administrator'],
    permissions: ['SchoolView'],
  },
  {
    id: 'forms.agency',
    title: 'navigation.forms.title',
    type: 'group',
    icon: 'heroicons_solid:clipboard-document-list',
    children: [
      {
        id: 'forms.agency.pdam-solicitud',
        title: 'navigation.forms.pdam-solicitud',
        type: 'basic',
        icon: 'heroicons_solid:document',
        link: '/forms/pdam-solicitud',
      },
      {
        id: 'forms.agency.psav-solicitud',
        title: 'navigation.forms.psav-solicitud',
        type: 'basic',
        icon: 'heroicons_solid:document',
        link: '/forms/psav-solicitud',
      },
    ],
    roles: ['Agency-Administrator'],
    permissions: ['FormView'],
  },
  {
    id: 'accounting.agency',
    title: 'navigation.accounting.title',
    type: 'group',
    icon: 'heroicons_solid:calculator',
    children: [
      {
        id: 'accounting.agency.budget',
        title: 'navigation.accounting.budget',
        type: 'basic',
        icon: 'heroicons_solid:document',
        link: '/accounting/agency/budget',
      },
      {
        id: 'accounting.agency.financial-management',
        title: 'navigation.accounting.financial-management',
        type: 'basic',
        icon: 'heroicons_solid:document',
      },
      {
        id: 'accounting.agency.employee-management',
        title: 'navigation.accounting.employee-management',
        type: 'basic',
        icon: 'heroicons_solid:document',
      },
      {
        id: 'accounting.agency.rations-form',
        title: 'navigation.accounting.rations-form',
        type: 'basic',
        icon: 'heroicons_solid:document',
      },
    ],
    roles: ['Agency-Administrator'],
    permissions: ['AccountingView'],
  },
  {
    id: 'dashboard.agency',
    title: 'navigation.dashboard',
    type: 'basic',
    icon: 'heroicons_solid:chart-pie',
    link: '/dashboard',
    roles: ['Agency-Administrator'],
    permissions: ['ReportView'],
  },
  {
    id: 'reports.agency',
    title: 'navigation.reports',
    type: 'basic',
    icon: 'heroicons_solid:document-chart-bar',
    link: '/reports',
    roles: ['Agency-Administrator'],
    permissions: ['ReportView'],
  },
];
