import { FuseNavigationItem } from '@fuse/components/navigation';

export const agencyNavigation: FuseNavigationItem[] = [
  {
    id: 'dashboard.agency',
    title: 'navigation.dashboard',
    type: 'basic',
    icon: 'heroicons_solid:home',
    link: '/dashboard',
    roles: ['Agency-Administrator', 'Agency-User'],
  },
  // {
  //   id: 'program-requests',
  //   title: 'navigation.program-requests',
  //   type: 'basic',
  //   icon: 'heroicons_outline:document-text',
  //   link: '/program-requests',
  //   //permissions: ['ProgramRequestView'],
  // },
  {
    id: 'legibility',
    title: 'navigation.legibility',
    type: 'basic',
    icon: 'heroicons_outline:document-text',
    link: '/legibility',
    permissions: ['LegibilityView'],
  },
//   {
//     id: 'users',
//     title: 'navigation.users.title',
//     type: 'group',
//     icon: 'heroicons_solid:user',
//     children: [
//       {
//         id: 'users.list',
//         title: 'navigation.users.list',
//         type: 'basic',
//         icon: 'mat_solid:list',
//         link: '/users',
//       },
//       {
//         id: 'users.add',
//         title: 'navigation.users.add',
//         type: 'basic',
//         icon: 'mat_solid:add',
//         link: '/users/add',
//       },
//       {
//         id: 'roles.list',
//         title: 'navigation.users.roles',
//         type: 'basic',
//         icon: 'mat_solid:lock',
//         link: '/users/roles',
//       },
//     ],
//   },
  // Otros ítems específicos de Agency-Administrator
  {
    id: 'documents.agency',
    title: 'navigation.documents',
    type: 'basic',
    icon: 'heroicons_solid:document-duplicate',
    link: '/documents',
    roles: ['Agency-Administrator'],
    permissions: ['DocumentView'],
  },
//   {
//     id: 'sites',
//     title: 'navigation.sites.title',
//     type: 'basic',
//     icon: 'heroicons_outline:academic-cap',
//     link: '/sites',
//     roles: ['Agency-Administrator'],
//     permissions: ['site.view'],
//   },
  {
    id: 'schools',
    title: 'navigation.schools',
    type: 'basic',
    icon: 'heroicons_solid:academic-cap',
    link: '/schools',
    roles: ['Agency-Administrator'],
    permissions: ['school.view'],
  },
  {
    id: 'forms.agency',
    title: 'navigation.forms.title',
    type: 'group',
    icon: 'heroicons_solid:clipboard-document-list',
    children: [
      {
        id: 'forms.agency.pdam-solicitud',
        title: 'navigation.forms.pdam-solicitud',
        type: 'basic',
        icon: 'heroicons_solid:document',
        link: '/forms/pdam-solicitud',
      },
      {
        id: 'forms.agency.psav-solicitud',
        title: 'navigation.forms.psav-solicitud',
        type: 'basic',
        icon: 'heroicons_solid:document',
        link: '/forms/psav-solicitud',
      },
    ],
    roles: ['Agency-Administrator'],
    permissions: ['FormView'],
  },
  {
    id: 'accounting.agency',
    title: 'navigation.accounting.title',
    type: 'group',
    icon: 'heroicons_solid:calculator',
    children: [
      {
        id: 'accounting.agency.budget',
        title: 'navigation.accounting.budget',
        type: 'basic',
        icon: 'heroicons_solid:document',
        link: '/accounting/agency/budget',
      },
      {
        id: 'accounting.agency.financial-management',
        title: 'navigation.accounting.financial-management',
        type: 'basic',
        icon: 'heroicons_solid:document',
      },
      {
        id: 'accounting.agency.employee-management',
        title: 'navigation.accounting.employee-management',
        type: 'basic',
        icon: 'heroicons_solid:document',
      },
      {
        id: 'accounting.agency.rations-form',
        title: 'navigation.accounting.rations-form',
        type: 'basic',
        icon: 'heroicons_solid:document',
      },
    ],
    roles: ['Agency-Administrator'],
    permissions: ['AccountingView'],
  },
  // {
  //   id: 'employees',
  //   title: 'navigation.employees',
  //   type: 'basic',
  //   icon: 'heroicons_solid:users',
  //   link: '/employees',
  //   roles: ['Agency-Administrator'],
  //   // permissions: ['EmployeeView'],
  // },
  {
    id: 'staff',
    title: 'navigation.staff.title',
    type: 'group',
    icon: 'heroicons_solid:user-group',
    children: [
      {
        id: 'staff.add',
        title: 'navigation.staff.add',
        type: 'basic',
        icon: 'mat_solid:add',
        link: '/staff/add',
        roles: ['Agency-Administrator'],
        permissions: ['staff.create'],
      },
      {
        id: 'staff.employees',
        title: 'navigation.staff.employees',
        type: 'basic',
        icon: 'heroicons_solid:users',
        link: '/staff/employees',
        roles: ['Agency-Administrator'],
        permissions: ['staff.view'],
      },
      {
        id: 'staff.board-members',
        title: 'navigation.staff.board-members',
        type: 'basic',
        icon: 'heroicons_solid:user-group',
        link: '/staff/board-members',
        roles: ['Agency-Administrator'],
        permissions: ['staff.view'],
      },
    ],
    roles: ['Agency-Administrator'],
    permissions: ['staff.view'],
  },
  {
    id: 'reports.agency',
    title: 'navigation.reports',
    type: 'basic',
    icon: 'heroicons_solid:document-chart-bar',
    link: '/reports',
    roles: ['Agency-Administrator'],
    permissions: ['ReportView'],
  },
];
