import { inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from 'environments/environment';
import { getHttpOptions } from '../utils';
import { QueryParameters } from '../models/QueryParameters';
import { MessageTemplate } from '../models/MessageTemplate';

@Injectable({
  providedIn: 'root',
})
export class MessageTemplateService {
  private apiUrl = `${environment.baseHttpUrl}/message-template`;
  private _httpClient = inject(HttpClient);

  /**
   * Fetches a message template by ID from the API
   * @param queryParameters Query parameters including the template ID
   * @returns Observable with the message template data
   */
  getMessageTemplateById(queryParameters: QueryParameters): Observable<any> {
    return this._httpClient.get(
      `${this.apiUrl}/get-message-template-by-id`,
      getHttpOptions(queryParameters)
    );
  }

  /**
   * Fetches a message template by key from the API
   * @param queryParameters Query parameters including the template key
   * @returns Observable with the message template data
   */
  getMessageTemplateByKey(queryParameters: QueryParameters): Observable<any> {
    return this._httpClient.get(
      `${this.apiUrl}/get-message-template-by-key`,
      getHttpOptions(queryParameters)
    );
  }

  /**
   * Fetches all message templates from the API
   * @param queryParameters Query parameters for pagination and filtering
   * @returns Observable with the list of message templates
   */
  getAllMessageTemplates(queryParameters: QueryParameters): Observable<any> {
    return this._httpClient.get(
      `${this.apiUrl}/get-all-message-templates`,
      getHttpOptions(queryParameters)
    );
  }

  /**
   * Inserts a new message template
   * @param messageTemplate The message template to insert (id is optional as it's generated by the backend)
   * @returns Observable with the result
   */
  insertMessageTemplate(messageTemplate: Omit<MessageTemplate, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>): Observable<any> {
    return this._httpClient.post(
      `${this.apiUrl}/insert-message-template`,
      messageTemplate,
      getHttpOptions({})
    );
  }

  /**
   * Updates an existing message template
   * @param messageTemplate The message template to update
   * @returns Observable with the result
   */
  updateMessageTemplate(messageTemplate: Partial<MessageTemplate>): Observable<any> {
    return this._httpClient.put(
      `${this.apiUrl}/update-message-template`,
      messageTemplate,
      getHttpOptions({})
    );
  }
}

