/**
 * Códigos de error estandarizados para la API (Enum)
 */
export enum ErrorCode {
    // Generales
    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',

    // Datos / CRUD
    ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
    ENTITY_ALREADY_EXISTS = 'ENTITY_ALREADY_EXISTS',
    RELATED_DATA_PROTECTED = 'RELATED_DATA_PROTECTED',
    FIELD_TOO_LONG = 'FIELD_TOO_LONG',

    // Agencia
    AGENCY_NOT_FOUND = 'AGENCY_NOT_FOUND',
    AGENCY_ACCESS_DENIED = 'AGENCY_ACCESS_DENIED',

    // Sitio
    SITE_NOT_FOUND = 'SITE_NOT_FOUND',
    SITE_ACCESS_DENIED = 'SITE_ACCESS_DENIED',
    SITE_ALREADY_EXISTS = 'SITE_ALREADY_EXISTS',
    FIRST_SITE_MUST_BE_COMEDOR = 'FIRST_SITE_MUST_BE_COMEDOR',
    SCHOOL_MUST_HAVE_COMEDOR_FIRST = 'SCHOOL_MUST_HAVE_COMEDOR_FIRST',
    SITE_DATES_OUTSIDE_COMEDOR_RANGE = 'SITE_DATES_OUTSIDE_COMEDOR_RANGE',
    ONE_COMEDOR_PER_SCHOOL = 'ONE_COMEDOR_PER_SCHOOL',
    MISSING_STRONG_SERVICE = 'MISSING_STRONG_SERVICE',
    INSUFFICIENT_TIME_BETWEEN_SERVICES = 'INSUFFICIENT_TIME_BETWEEN_SERVICES',

    // Escuela
    SCHOOL_NOT_FOUND = 'SCHOOL_NOT_FOUND',

    // Staff
    STAFF_NOT_FOUND = 'STAFF_NOT_FOUND'
}
