// Esto es para usar cuando no están los servicios de la API disponibles
export const optionSelectionData = [
    {
        id: 17,
        name: 'Tipo de cocina 1',
        nameEN: 'Kitchen Type 1',
        optionKey: 'typesOfKitchen',
        isActive: true,
        booleanValue: false,
        displayOrder: 18,
    },
    {
        id: 18,
        name: 'Tipo de cocina 2',
        nameEN: 'Kitchen Type 2',
        optionKey: 'typesOfKitchen',
        isActive: true,
        booleanValue: false,
        displayOrder: 19,
    },
    {
        id: 19,
        name: 'Tipo de cocina 3',
        nameEN: 'Kitchen Type 3',
        optionKey: 'typesOfKitchen',
        isActive: true,
        booleanValue: false,
        displayOrder: 20,
    },
    {
        id: 20,
        name: 'Tipo de grupo 1',
        nameEN: 'Group Type 1',
        optionKey: 'typesOfGroup',
        isActive: true,
        booleanValue: false,
        displayOrder: 21,
    },
    {
        id: 21,
        name: 'Tipo de grupo 2',
        nameEN: 'Group Type 2',
        optionKey: 'typesOfGroup',
        isActive: true,
        booleanValue: false,
        displayOrder: 22,
    },
    {
        id: 22,
        name: 'Tipo de grupo 3',
        nameEN: 'Group Type 3',
        optionKey: 'typesOfGroup',
        isActive: true,
        booleanValue: false,
        displayOrder: 23,
    },
    {
        id: 23,
        name: 'Tipo de entrega 1',
        nameEN: 'Delivery Type 1',
        optionKey: 'typesOfDelivery',
        isActive: true,
        booleanValue: false,
        displayOrder: 24,
    },
    {
        id: 24,
        name: 'Tipo de entrega 2',
        nameEN: 'Delivery Type 2',
        optionKey: 'typesOfDelivery',
        isActive: true,
        booleanValue: false,
        displayOrder: 25,
    },
    {
        id: 25,
        name: 'Tipo de entrega 3',
        nameEN: 'Delivery Type 3',
        optionKey: 'typesOfDelivery',
        isActive: true,
        booleanValue: false,
        displayOrder: 26,
    },
    {
        id: 26,
        name: 'Tipo de auspiciador 1',
        nameEN: 'Sponsor Type 1',
        optionKey: 'typesOfSponsor',
        isActive: true,
        booleanValue: false,
        displayOrder: 27,
    },
    {
        id: 27,
        name: 'Tipo de auspiciador 2',
        nameEN: 'Sponsor Type 2',
        optionKey: 'typesOfSponsor',
        isActive: true,
        booleanValue: false,
        displayOrder: 28,
    },
    {
        id: 28,
        name: 'Tipo de auspiciador 3',
        nameEN: 'Sponsor Type 3',
        optionKey: 'typesOfSponsor',
        isActive: true,
        booleanValue: false,
        displayOrder: 29,
    },
    {
        id: 29,
        name: 'Política de operación 1',
        nameEN: 'Operating Policy 1',
        optionKey: 'typesOfOperatingPolicy',
        isActive: true,
        booleanValue: false,
        displayOrder: 30,
    },
    {
        id: 30,
        name: 'Política de operación 2',
        nameEN: 'Operating Policy 2',
        optionKey: 'typesOfOperatingPolicy',
        isActive: true,
        booleanValue: false,
        displayOrder: 31,
    },
    {
        id: 31,
        name: 'Política de operación 3',
        nameEN: 'Operating Policy 3',
        optionKey: 'typesOfOperatingPolicy',
        isActive: true,
        booleanValue: false,
        displayOrder: 32,
    },
];
