// Esto es para usar cuando no estan los servicios de la API disponibles
export const optionSelectionData = [
    {
        id: 1,
        name: 'Si',
        nameEN: 'Yes',
        optionKey: 'yesNo',
        isActive: true,
        booleanValue: 1,
        displayOrder: 1,
    },
    {
        id: 2,
        name: 'No',
        nameEN: 'No',
        optionKey: 'yesNo',
        isActive: true,
        booleanValue: 0,
        displayOrder: 2,
    },
    {
        id: 3,
        name: 'En Proceso',
        nameEN: 'In Progress',
        optionKey: 'exceptionStatus',
        isActive: true,
        booleanValue: 0,
        displayOrder: 4,
    },
    {
        id: 4,
        name: 'Otorgado',
        nameEN: 'Granted',
        optionKey: 'taxExemptionStatus',
        isActive: true,
        booleanValue: 0,
        displayOrder: 5,
    },
    {
        id: 5,
        name: 'Denegada',
        nameEN: 'Denied',
        optionKey: 'taxExemptionStatus',
        isActive: true,
        booleanValue: 0,
        displayOrder: 6,
    },
    {
        id: 6,
        name: 'Semanal',
        nameEN: 'Weekly',
        optionKey: 'incomeFrequency',
        isActive: true,
        booleanValue: 0,
        displayOrder: 7,
    },
    {
        id: 7,
        name: 'Quincenal',
        nameEN: 'Bi-weekly',
        optionKey: 'incomeFrequency',
        isActive: true,
        booleanValue: 0,
        displayOrder: 8,
    },
    {
        id: 8,
        name: 'Bi semestral',
        nameEN: 'Bi-semestral',
        optionKey: 'incomeFrequency',
        isActive: true,
        booleanValue: 0,
        displayOrder: 9,
    },
    {
        id: 9,
        name: 'Mensual',
        nameEN: 'Monthly',
        optionKey: 'incomeFrequency',
        isActive: true,
        booleanValue: 0,
        displayOrder: 10,
    },
    {
        id: 10,
        name: 'Anual',
        nameEN: 'Annual',
        optionKey: 'incomeFrequency',
        isActive: true,
        booleanValue: 0,
        displayOrder: 11,
    },
    {
        id: 11,
        name: 'Estatal',
        nameEN: 'State',
        optionKey: 'taxExemptionType',
        isActive: true,
        booleanValue: 0,
        displayOrder: 12,
    },
    {
        id: 12,
        name: 'Federal',
        nameEN: 'Federal',
        optionKey: 'taxExemptionType',
        isActive: true,
        booleanValue: 0,
        displayOrder: 13,
    },
    {
        id: 13,
        name: 'Gobierno',
        nameEN: 'Government',
        optionKey: 'typeOfEntity',
        isActive: true,
        booleanValue: 0,
        displayOrder: 14,
    },
    {
        id: 14,
        name: 'Privado',
        nameEN: 'Private',
        optionKey: 'typeOfEntity',
        isActive: true,
        booleanValue: 0,
        displayOrder: 15,
    },
    {
        id: 15,
        name: 'Laico',
        nameEN: 'Laic',
        optionKey: 'typeOfApplicant',
        isActive: true,
        booleanValue: 0,
        displayOrder: 16,
    },
    {
        id: 16,
        name: 'Base de fe',
        nameEN: 'Faith-based',
        optionKey: 'typeOfApplicant',
        isActive: true,
        booleanValue: 0,
        displayOrder: 17,
    },
];
